site_name: Castor documentation
site_url: https://pyrech.github.io/castor-test/
repo_url: https://github.com/jolicode/castor
copyright: 'Castor is licensed under <a href="https://github.com/jolicode/castor/blob/main/LICENSE">MIT license</a>'

edit_uri: edit/main/doc/
docs_dir: doc
nav:
  - Home: ../README.md
  - 'Getting started':
      - 'Installation and autocomplete': '01-installation.md'
      - 'Basic usage': '02-basic-usage.md'
      - 'Executing processes': '03-run.md'
      - 'Task arguments': '04-arguments.md'
      - 'Context': '05-context.md'
      - 'Reference': '06-reference.md'
  - 'Going further': 'going-further/'
  - Changelog: ../CHANGELOG.md

theme:
  name: material
  logo: assets/logo_CASTOR_line.svg
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      scheme: default
      primary: white
      accent: amber
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - content.action.edit
    - content.tabs.link
    - navigation.path
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.sections
    - search.highlight
  #custom_dir: doc/overrides
extra_css:
  - style.css

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/jolicode
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/jolicode
  generator: false

markdown_extensions:
  - admonition
  - attr_list
  - github-callouts
  - footnotes
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      permalink: true
