site_name: The DX oriented task runner in PHP
site_url: https://castor.jolicode.com/
repo_url: https://github.com/jolicode/castor
copyright: 'Castor is licensed under <a href="https://github.com/jolicode/castor/blob/main/LICENSE">MIT license</a>'

edit_uri: edit/main/doc/
docs_dir: doc
exclude_docs: |
  doc/overrides
  doc/_nav.md

theme:
  name: material
  logo: assets/logo_CASTOR_line.svg
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github
  language: en
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      scheme: default
      primary: white
      accent: amber
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - content.action.edit
    - content.code.copy
    - content.tabs.link
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - toc.integrate
  custom_dir: doc/overrides

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/jolicode
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/jolicode
  generator: false

markdown_extensions:
  - admonition
  - attr_list
  - github-callouts
  - footnotes
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: false
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - toc:
      permalink: true

plugins:
  - search
  - literate-nav:
      nav_file: _nav.md

extra_javascript:
  - assets/javascripts/highlight.min.js
extra_css:
  - assets/stylesheets/highlight-github.min.css
